### 4.1 Creating DataFrame using dictionary data

In [2]:
import pandas as pd
cities = {'Dhaka' : [1,2,3,4], 'Chittagong' : [5,6,7,8]}
df1 = pd.DataFrame(cities)
df1

   Dhaka  Chittagong
0      1           5
1      2           6
2      3           7
3      4           8

### 4.2 Creating DataFrame using list data

#### 4.2.1 Creating single column
        df = pd.DataFrame(lst)

In [14]:
import pandas as pd
city = ['dhaka', 'chittagong', 'sylhet', 'khulna']
df421 = pd.DataFrame(city)
df421

            0
0       dhaka
1  chittagong
2      sylhet
3      khulna

#### 4.2.2 Creating multiple columns
The main point to note here is the length of each list should be same. If
the length does not match, we’ll get an error.

In [13]:
import pandas as pd
name = ['dhaka', 'chittagong', 'sylhet', 'khulna']
area = [1200, 2000, 3000, 4000]
df422 = pd.DataFrame(list(zip(name, area)))
df422

            0     1
0       dhaka  1200
1  chittagong  2000
2      sylhet  3000
3      khulna  4000

#### 4.3 Adding custom column name
This is done by a parameter ‘column’. 

df = pd.DataFrame(data, columns=[‘col1, ‘col2])

In [17]:
df43 = pd.DataFrame(list(zip(name, area)), columns = ['Name', 'Area'])
df43

         Name  Area
0       dhaka  1200
1  chittagong  2000
2      sylhet  3000
3      khulna  4000

#### 4.4 creating DataFrame from list of dictionaries
Each element (dict) of the list will become a row and the dictionary key value pair will become
column and its value.

In [18]:
list_dict = [{'Name': 'dhaka', 'Area': 1200}, {'Name': 'chittagong', 'Area': 2000}, {'Name': 'sylhet', 'Area': 3000}, {'Name': 'khulna', 'Area': 4000}]
df44 = pd.DataFrame(list_dict)
df44

         Name  Area
0       dhaka  1200
1  chittagong  2000
2      sylhet  3000
3      khulna  4000

#### 4.5 creating DataFrame from other files
DataFrame can be created from other file types too like CSV, MS Excel.

df = pd.read_csv('csvName.csv')

df = pd.read_excel('excelFileName.xlsx')

#### 4.6 Creating blank DataFrame
df = pd.DataFrame

In [19]:
df46 = pd.DataFrame
df46

pandas.core.frame.DataFrame

In [20]:
# We can add the column names if we know it in advance by:
df46 = pd.DataFrame(columns=['name', 'age'])
df46

Empty DataFrame
Columns: [name, age]
Index: []