#### 5. Basics of DataFrames

In [50]:
import pandas as pd 
df5 = pd.read_csv('bike.csv')
df5.head()

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt
0,1,1/1/2011,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,16
1,2,1/1/2011,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,40
2,3,1/1/2011,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,32
3,4,1/1/2011,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,13
4,5,1/1/2011,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,1

#### 5.2 Shape of the DataFrame
DataFrame is a two-dimensional matrix and will give the shape as rows and
columns by

`df.shape`

In [4]:
df5.shape

(17379, 15)

This is a tuple and thus if we need to store the rows and columns into some
variables

`rows, columns = df.shape`

In [5]:
rows, columns = df5.shape
print("Rows : ", rows)
print("Columns : ", columns)

Rows :  17379
Columns :  15

#### 5.3 Top ‘n’ rows
`df.head()` gives us the top 5 entries by default

In [6]:
df5.head()

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt
0,1,1/1/2011,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,16
1,2,1/1/2011,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,40
2,3,1/1/2011,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,32
3,4,1/1/2011,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,13
4,5,1/1/2011,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,1

If we need top 3 entries the we just need to pass that value to the head().

In [7]:
df5.head(3)

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt
0,1,1/1/2011,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,16
1,2,1/1/2011,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,40
2,3,1/1/2011,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,32

#### 5.4 Last ‘n’ row
As head method we have tail method as well.

`df.tail()` # Last 5 record

`df.tail(3)` # Last 3 record

#### 5.5 Range of entries
We can even extract a range of entries from somewhere in the DataFrame by

`df[5, 8]`

here, important point is that this will include row #5 an exclude row #8. (5,6,7)

In [10]:
df5[5:8]
# To access all the rows df[:] or just df will work

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt
5,6,1/1/2011,1,0,1,5,0,6,0,2,0.24,0.2576,0.75,0.0896,1
6,7,1/1/2011,1,0,1,6,0,6,0,1,0.22,0.2727,0.80,0.0000,2
7,8,1/1/2011,1,0,1,7,0,6,0,1,0.20,0.2576,0.86,0.0000,3

#### 5.6 Accessing the columns
we may need to know the columns present in the data.

`df.columns`

In [11]:
df5.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed', 'cnt'],
      dtype='object')

To get the individual column data we can do

In [12]:
df5.weekday

0        6
1        6
2        6
3        6
4        6
        ..
17374    1
17375    1
17376    1
17377    1
17378    1
Name: weekday, Length: 17379, dtype: int64

OR

In [13]:
df5['weekday']

0        6
1        6
2        6
3        6
4        6
        ..
17374    1
17375    1
17376    1
17377    1
17378    1
Name: weekday, Length: 17379, dtype: int64

#### 5.7 Accessing ‘n’ columns

In [15]:
df5[['holiday','weekday']].head(3)

   holiday  weekday
0        0        6
1        0        6
2        0        6

#### 5.8 Type of column

In [16]:
type(df5['weekday'])

pandas.core.series.Series

### 5.9 Basic operations on column

###### 5.9.1 maximum
We can get the maximum value of a column by:
`df[“age”].max()`

In [17]:
df5['temp'].max()

1.0

###### 5.9.2 minimum
`df[“age”].min()`

In [18]:
df5['temp'].min()

0.02

###### 5.9.3 mean. The mean can be simply defined as the average of numbers.
`df[“age”].mean()` # Average

In [19]:
df5['temp'].mean()

0.4969871684216583

###### 5.9.4 standard deviation. The Standard Deviation denoted by sigma is a measure of the spread of numbers.
`df[“age”].std()`

In [20]:
df5['temp'].std()

0.19255612124972407

#### 5.10 Describe the DataFrame
We can get the detail of all the data in the DataFrame like it’s max, min,
mean etc. 

`df.describe()`

In [21]:
df5.describe()

,instant,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt
count,17379.0000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000
mean,8690.0000,2.501640,0.502561,6.537775,11.546752,0.028770,3.003683,0.682721,1.425283,0.496987,0.475775,0.627229,0.190098,189.463088
std,5017.0295,1.106918,0.500008,3.438776,6.914405,0.167165,2.005771,0.465431,0.639357,0.192556,0.171850,0.192930,0.122340,181.387599
min,1.0000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.020000,0.000000,0.000000,0.000000,1.000000
25%,4345.5000,2.000000,0.000000,4.000000,6.000000,0.000000,1.000000,0.000000,1.000000,0.340000,0.333300,0.480000,0.104500,40.000000
50%,8690.0000,3.000000,1.000000,7.000000,12.000000,0.000000,3.000000,1.000000,1.000000,0.500000,0.484800,0.630000,0.194000,142.000000
75%,13034.5000,3.000000,1.000000,10.000000,18.000000,0.000000,5.000000,1.000000,2.000000,0.660000,0.621200,0.780000,0.253700,281.000000
max,17379.0000,4.000000,1.000000,12.000000,23.000000,1.000000,6.000000,1.000000,4.000000,1.000000,1.000000,1.000000,0.850700,977.000000

#### 5.11 Conditional operation on columns
If we want the rows where holiday is greater than 0 in the DataFrame then

In [28]:
df5[df5['holiday'] > 0].head(3)

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt
372,373,1/17/2011,1,0,1,0,1,1,0,2,0.20,0.1970,0.47,0.2239,17
373,374,1/17/2011,1,0,1,1,1,1,0,2,0.20,0.1970,0.44,0.1940,16
374,375,1/17/2011,1,0,1,2,1,1,0,2,0.18,0.1667,0.43,0.2537,8

If we want the row with minimum temp

In [31]:
df5[df5['temp'] == df5['temp'].min()]

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt
483,484,1/22/2011,1,0,1,4,0,6,0,2,0.02,0.0152,0.48,0.2985,3
484,485,1/22/2011,1,0,1,6,0,6,0,2,0.02,0.0303,0.44,0.2239,2
485,486,1/22/2011,1,0,1,7,0,6,0,1,0.02,0.0152,0.44,0.2836,8
486,487,1/22/2011,1,0,1,8,0,6,0,1,0.02,0.0000,0.44,0.3284,27
504,505,1/23/2011,1,0,1,2,0,0,0,1,0.02,0.0606,0.62,0.1343,18
505,506,1/23/2011,1,0,1,3,0,0,0,1,0.02,0.0606,0.62,0.1343,5
528,529,1/24/2011,1,0,1,4,0,1,1,1,0.02,0.0606,0.48,0.1343,1
529,530,1/24/2011,1,0,1,5,0,1,1,1,0.02,0.0606,0.48,0.1343,5
530,531,1/24/2011,1,0,1,6,0,1,1,1,0.02,0.0758,0.48,0.0896,15
531,532,1/24/2011,1,0,1,7,0,1,1,1,0.02,0.1212,0.48,0.0000,84
8718,8719,1/4/2012,1,1,1,2,0,3,1,1,0.02,0.0152,0.34,0.2836,1
8719,8720,1/4/2012,1,1,1,3,0,3,1,1,0.02,0.0152,0.34,0.2836,1
8720,8721,1/4/2012,1,1,1,4,0,3,1,1,0.02,0.0455,0.41,0.1940,2
8721,8722,1/4/2012,1,1,1,5,0,3,1,1,0.02,0.0455,0.41,0.1940,14
8722,8723,1/4/2012,1,1,1,6,0,3,1,1,0.02,0.0455,0.41,0.1642,59
8723,8724,1/4/2012,1,1,1,7,0,3,1,1,0.02,0.0455,0.44,0.1940,152
8724,8725,1/4/2012,1,1,1,8,0,3,1,1,0.02,0.0606,0.44,0.1343,315

If we want only the name of the temp whose hr is Greter  than 22 then,

In [39]:
df5['temp'][df5['hr'] > 22]

23       0.46
46       0.22
68       0.18
91       0.20
114      0.20
         ...
17282    0.24
17306    0.24
17330    0.26
17354    0.20
17378    0.26
Name: temp, Length: 728, dtype: float64

if we need two columns like "temp" and "hr"

In [41]:
df5[['temp', 'hr']][df5['hr'] > 22]

       temp  hr
23     0.46  23
46     0.22  23
68     0.18  23
91     0.20  23
114    0.20  23
...     ...  ..
17282  0.24  23
17306  0.24  23
17330  0.26  23
17354  0.20  23
17378  0.26  23

[728 rows x 2 columns]

#### 5.12 accessing row with loc and iloc
Here, loc and iloc are same, this is because we have not set any index here. Index here is by default incremental integers. Loc takes the index value and gives the result for that index, whereas iloc takes the position of an index and gives the row. We can see the difference if we change the default index. In real problems we mostly set the index to the actual data.

`df.loc[<index>]` and `df.iloc[<index position>]`

`df.loc[0]` and `df.iloc[0]`

#### 5.13 Set index
Index by default comes as an incremental integer (0,1…n)

In [42]:
df5.index

RangeIndex(start=0, stop=17379, step=1)

we can change this to the actual data as:

`df.set_index(“Column Name”)`

In [44]:
df5.set_index('temp').head(2)

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,atemp,hum,windspeed,cnt
temp,,,,,,,,,,,,,,
0.24,1,1/1/2011,1,0,1,0,0,6,0,1,0.2879,0.81,0.0,16
0.22,2,1/1/2011,1,0,1,1,0,6,0,1,0.2727,0.80,0.0,40

This is correct but has a problem. This command gives a new DataFrame and
does not change the existing one.

In [51]:
df5.head(2)

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt
0,1,1/1/2011,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,16
1,2,1/1/2011,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,40

To make the change effective to the existing one, there are two ways.

1. Store the new DataFrame to the existing one

        `df = df.set_index(“Column name”)`

OR

2. We have a parameter called ‘inplace’ which can be set to true to make the
change effective to the existing DataFrame.
    
        `df.set_index("Column name", inplace=True)`

In [52]:
# df5 = df5.set_index('temp')
df5.set_index('temp', inplace=True)
df5.head(2)

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,atemp,hum,windspeed,cnt
temp,,,,,,,,,,,,,,
0.24,1,1/1/2011,1,0,1,0,0,6,0,1,0.2879,0.81,0.0,16
0.22,2,1/1/2011,1,0,1,1,0,6,0,1,0.2727,0.80,0.0,40

Now we can see the difference of loc and iloc also

Now we can see that the loc is taking the index value i.e. temp (.24) where
as iloc gives result for the position of zero (.22).

In [53]:
df5.loc[0.24]

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,atemp,hum,windspeed,cnt
temp,,,,,,,,,,,,,,
0.24,1,1/1/2011,1,0,1,0,0,6,0,1,0.2879,0.81,0.0000,16
0.24,4,1/1/2011,1,0,1,3,0,6,0,1,0.2879,0.75,0.0000,13
0.24,5,1/1/2011,1,0,1,4,0,6,0,1,0.2879,0.75,0.0000,1
0.24,6,1/1/2011,1,0,1,5,0,6,0,2,0.2576,0.75,0.0896,1
0.24,9,1/1/2011,1,0,1,8,0,6,0,1,0.2879,0.75,0.0000,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0.24,17339,12/30/2012,1,1,12,7,0,0,0,1,0.2121,0.56,0.3582,13
0.24,17340,12/30/2012,1,1,12,8,0,0,0,1,0.1970,0.52,0.4627,33
0.24,17341,12/30/2012,1,1,12,9,0,0,0,1,0.2121,0.52,0.3881,74
0.24,17350,12/30/2012,1,1,12,18,0,0,0,2,0.2121,0.44,0.2985,125
0.24,17368,12/31/2012,1,1,12,12,0,1,1,2,0.2273,0.56,0.1940,224

In [54]:
df5.iloc[0]

instant              1
dteday        1/1/2011
season               1
yr                   0
mnth                 1
hr                   0
holiday              0
weekday              6
workingday           0
weathersit           1
atemp           0.2879
hum               0.81
windspeed          0.0
cnt                 16
Name: 0.24, dtype: object