### 6.1 Reading CSV

#### 6.1.1 Reading

Let’s look at the way to read a csv data: `df = pd.read_csv(<csvName>)`

In [2]:
import pandas as pd
df_csv = pd.read_csv('bike.csv')
df_csv.head(3)

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt
0,1,1/1/2011,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,16
1,2,1/1/2011,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,40
2,3,1/1/2011,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,32

#### 6.1.2 Removing header

We can remove the headers present in the CSV if we don’t need them.
`df = pd.read_csv("name_age.csv", header=None)`

In [4]:
df_no_header = pd.read_csv('bike.csv', header=None)
df_no_header.head(3)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt
1,1,1/1/2011,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0,16
2,2,1/1/2011,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0,40

#### 6.1.3 Adding custom header

`df = pd.read_csv("name_age.csv", names=["NAME", "AGE", "dateOfBirth", "GENDER"])`

In [5]:
df_custom_header = pd.read_csv('bike.csv', header=None, names=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o'])
df_custom_header.head(3)

,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o
0,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt
1,1,1/1/2011,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0,16
2,2,1/1/2011,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0,40

#### 6.1.4 Reading specific rows

We can use head/tail etc. to access specific data in DataFrame but we can
also read specific rows from CSV as:

`df = pd.read_csv("name_age.csv", nrows=4)`

In [8]:
df_row = pd.read_csv('bike.csv', nrows=3)
# The value in ‘nrows’ will be the number of rows we want to see, and this will except the header.
df_row

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt
0,1,1/1/2011,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0,16
1,2,1/1/2011,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0,40
2,3,1/1/2011,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0,32

#### 6.1.5 Reading the data from specific row

`df = pd.read_csv("name_age.csv", skiprows=2)`

This will skip the first two rows in the csv and start the data from 3rd row

In [3]:
df_skip = pd.read_csv('bike.csv', skiprows=2)
df_skip.head(3)

   2  1/1/2011  1  0  1.1  1.2  0.1  6  0.2  1.3  0.22  0.2727   0.8  0.3  40
0  3  1/1/2011  1  0    1    2    0  6    0    1  0.22  0.2727  0.80  0.0  32
1  4  1/1/2011  1  0    1    3    0  6    0    1  0.24  0.2879  0.75  0.0  13
2  5  1/1/2011  1  0    1    4    0  6    0    1  0.24  0.2879  0.75  0.0   1

##### The alternate way is to specify the row of the header as:

`df = pd.read_csv("name_age.csv", header=2)`

header=2 means the third row in csv as the indexing starts from 0.

In [4]:
df_alt = pd.read_csv("bike.csv", header=2)
df_alt.head(3)

   2  1/1/2011  1  0  1.1  1.2  0.1  6  0.2  1.3  0.22  0.2727   0.8  0.3  40
0  3  1/1/2011  1  0    1    2    0  6    0    1  0.22  0.2727  0.80  0.0  32
1  4  1/1/2011  1  0    1    3    0  6    0    1  0.24  0.2879  0.75  0.0  13
2  5  1/1/2011  1  0    1    4    0  6    0    1  0.24  0.2879  0.75  0.0   1

#### 6.1.6 Cleaning NA data

 NAN (not a number)

if data has its own convention of telling NAN (like NA, not available etc.) then we have to convert them to NAN format so that we can clean them later.

`df = pd.read_csv("name_age.csv", na_values=["na", "not available"])`

`Best Practice - ` we can apply cleaning only to particular columns we can use dictionaries as.

`df = pd.read_csv("name_age.csv", na_values={"gender" : ["na", "not available"]})`

The cleaning has been applied to a specific column.

### 6.2 Writing to CSV

`df.to_csv(<fileName>)`

#### 6.2.1 Avoiding index

`df.to_csv("newCSV.csv", index=False)`

#### 6.2.2 Writing only specific columns

`df.to_csv("newCSV.csv", columns=["name", "age"], index=False)`

#### 6.2.3 Avoid writing headers

`df.to_csv("newCSV.csv", header=False)`

### 6.3 Read Excel

`df_new = pd.read_excel("personsData.xlsx")`

In [21]:
import pandas as pd
df_xlsx = pd.read_excel("student.xlsx")
df_xlsx.head(3)

   NO  Name  AHE  Percentage
0   1  alif   21        0.80
1   2   baa   22        0.77
2   4   taa   23        0.66

#### 6.3.1 Reading sheets

excel is known for sheets, by default the ‘read_excel()’ takes the 1 st sheet of
the excel. But if we can specify specific sheet as well.

`df_sheet = pd.read_excel("excel_file_name.xlsx", 'Sheet_name')`

In [24]:
df_sheet = pd.read_excel("student.xlsx", 'Sheet2')
df_sheet.head(3)

   NO  Name  AHE  Percentage Gender
0   1  alif   21        0.80      f
1   2   baa   22        0.77      m
2   4   taa   23        0.66      f

#### 6.3.2 Passing function to columns

For example, we wrote a function to convert gender (from “m” to “Male” and
“f” to “Female”)

`df_new = pd.read_excel("personsData.xlsx", converters = {
"gender" : Function_name
})`

In [28]:
def convert_to_complete_gender(Gender):
    if Gender == 'm':
        return 'Male'
    elif Gender == 'f':
        return 'Female'
    else:
        return "NA"
df_sheet_def = pd.read_excel("student.xlsx", converters={'Gender': convert_to_complete_gender})
df_sheet_def.head(3)

   NO  Name  AHE  Percentage  Gender
0   1  alif   21        0.80  Female
1   2   baa   22        0.77    Male
2   4   taa   23        0.66  Female

We can supply the sheet name also:

`df_new = pd.read_excel("personsData.xlsx", sheet_name = "data",
converters = {
"gender" : completeGender
})`

#### 6.3.3 Some basic common functions in read_excel and read_csv are:

The use of some very basic parameters in excel and csv are same as:
`‘header’`, `‘index’`, `‘skiprows’`, `‘nrows’`, `‘na_values’` etc. which are covered
above.

### 6.4 Writing excels

`df_new.to_excel("newExcel.xlsx")`

This by default takes the sheet name as “sheet1”

#### 6.4.1 Writing to a custom sheet name 

`df_new.to_excel("newExcel.xlsx", sheet_name="new_sheet")`

#### 6.4.2 Avoid index 

`df_new.to_excel("newExcel.xlsx", sheet_name="new_sheet", index=False)`

#### 6.4.3 Avoid headers

`df_new.to_excel("newExcel.xlsx", sheet_name="new_sheet", header=False)`

#### 6.4.4 write at a particular row and column

`df_new.to_excel("newExcel.xlsx", sheet_name="new_sheet", index=False,
startrow=1, startcol=2)`

write start from (1, 2) cell.  (indexing starts from 0)

#### 6.4.5 Writing multiple sheets to the same excel file

Let’s create two data frames and write that in different sheets of the Excel.

`df_new.to_excel("newExcel.xlsx", sheet_name="new_sheet_1")`

`df_new.to_excel("newExcel.xlsx", sheet_name="new_sheet_2")`

And then using ExcelWriter() we can write to multiple sheets:
with pd.ExcelWriter("multipleSheet.xlsx") as writer:

`df1.to_excel(writer, sheet_name="data1")`

`df2.to_excel(writer, sheet_name="data2")`

#### 6.5 Reading and writing txt file

The data can be provided in txt format also, but the important point is there
has to be a delimiter in the data (whitespaces or tabs are also fine)

#### 6.5.1 Reading txt

`df = pd.read_csv("text.txt",delimiter="\t")`

Here, the delimiter is “tab”

#### 6.5.2 Writing to txt

`df.to_csv(“test.txt”, sep='\t', index=False)`